name: integration

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'yarn.lock'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'yarn.lock'

jobs:
  no-auth:
    name: Download w/o auth
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show version
        uses: ./
        with:
          command: version
          options: --client

      - name: Set Windows binary name
        if: ${{ matrix.os == 'windows-latest' }}
        run: echo "ARGOCD_BINARY_NAME=argocd.exe" >> $GITHUB_ENV

      - name: Check install - should not re-download
        uses: ./

  with-auth:
    name: Download with auth
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show version
        uses: ./
        env:
          # Only required for first step in workflow where API is called
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: version
          options: --client

      - name: Set Windows binary name
        if: ${{ matrix.os == 'windows-latest' }}
        run: echo "ARGOCD_BINARY_NAME=argocd.exe" >> $GITHUB_ENV

      - name: Check install - should not re-download
        uses: ./

  set-version:
    name: Set version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show version
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 1.8.0
          command: version
          options: --client
